FROM node:20-alpine AS builder
WORKDIR /app

# Copy package files and install ONLY production dependencies
COPY package*.json ./
RUN npm ci --omit=dev


FROM node:20-alpine
WORKDIR /app


COPY --from=builder /app/node_modules ./node_modules

COPY . .


ARG PORT=3000
ENV PORT=${PORT}
EXPOSE ${PORT}
USER node

CMD ["node", "index.js"]
